### ISSUE TITLE
Doesn't work with 1.6.640

### ISSUE THREAD

**Issue by bwanshoom** [Tpiac/Skyrim-REMASTERED#1]
Despite what the README says, it doesn't support 1.6.640. The wabbajack installation appears to only be looking for 1.6.1130 game files. The log is full of errors similar to the following:
 
00:19:49.624 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccBGSSSE001-Fish.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1130.0|data\ccbgssse001-fish.esm)

**Comment by Tpiac** [comment]
Well, maybe you right. I checked only 1.6.1130 version.

However it is straighforward to update game in steam so nothing stops you from installing the list. I will update readme later
