### ISSUE TITLE
Executable paths in MO2 are borked

### ISSUE THREAD

**Issue by bwanshoom** [Tpiac/Skyrim-REMASTERED#2]
Most of the paths reference an S:/MODDING/Skyrim/TOOLS/. None of those tools are part of the install so they should all probably be removed from ModOrganizer.ini.

Broken paths:
* LOOT
* SSEEdit
* SSEEditQuickAutoClean
* Synthesis
* xLODGenx64
* TexGenx64
* DynDOLODx64
* EasyNPC

**Comment by Tpiac** [comment]
You are right. I missed that
